# Generated by Django 4.0.2 on 2022-02-18 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MedicalNewsImages',
            new_name='MedicalNewsImage',
        ),
    ]
