# Generated by Django 4.0.2 on 2022-02-18 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_medicalnewsimages_medicalnewsimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalNewsImageSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pictures', models.ImageField(blank=True, upload_to='medical_news')),
            ],
        ),
        migrations.DeleteModel(
            name='MedicalNewsImage',
        ),
    ]
