# Generated by Django 4.0.2 on 2022-02-18 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_hospital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='hospital_images',
            new_name='hospital_image',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='hospital_names',
            new_name='hospital_name',
        ),
    ]
