# Generated by Django 4.0.2 on 2022-02-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_hospital_images_hospital_hospital_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='hospital_detail',
            field=models.CharField(default='details', max_length=1000),
        ),
    ]
