# Generated by Django 4.0.2 on 2022-02-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_hospital_hospital_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='hospital_detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
